name: Generate PDF
on: [push]
jobs:
    build:
        runs-on: ubuntu-latest

        permissions:
            # Give the default GITHUB_TOKEN write permission to commit and push the
            # added or changed files to the repository.
            contents: write

        steps:
            - uses: actions/checkout@v4
              with:
                  ref: ${{ github.head_ref }}

            - name: Use Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: "20.x"

            - run: npm ci

            - run: npm run generate:latex

            - uses: xu-cheng/latex-action@v3
              with:
                  working_directory: template
                  root_file: output.tex
                  latexmk_use_xelatex: true

            - run: mv template/output.pdf "output/markrofail-cv.pdf"

            - run: npm run generate:png

            - uses: stefanzweifel/git-auto-commit-action@v5
              with:
                  commit_message: "[autogenerated] generated new pdf"
